import { app, BrowserWindow, ipcMain, webContents } from 'electron';
import { getDatabase, closeDatabase } from './services/database';
import { setupDatabase } from './services/database-setup';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Global mainWindow referansı
let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 1024,
    width: 1440,
    fullscreen: true, // Tam ekran başlat
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      webSecurity: false, // Local network için güvenlik kısıtlamalarını kaldır
    },
    // Pencere kontrolleri
    frame: true, // Başlık çubuğunu göster (F11 ile tam ekrandan çıkabilmek için)
    autoHideMenuBar: true, // Menü çubuğunu otomatik gizle
    icon: undefined, // İsteğe bağlı: İkon ekleyebilirsiniz
  });

  // CSP'yi devre dışı bırak - WebSocket için gerekli
  mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [''] // CSP'yi kaldır
      }
    });
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Tam ekran başlatma
  mainWindow.setFullScreen(true);
  
  // DevTools kapatıldı - production ready uygulama
  
  // F11 tuşu ile tam ekrandan çıkma/girme
  if (mainWindow) {
    mainWindow.webContents.on('before-input-event', (event, input) => {
      if (input.key === 'F11' && input.type === 'keyDown' && mainWindow) {
        mainWindow.setFullScreen(!mainWindow.isFullScreen());
      }
    });
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  // Veritabanını başlat
  try {
    const db = getDatabase();
    console.log('✅ SQLite veritabanı başarıyla başlatıldı!');
    console.log('📍 Veritabanı yolu:', db.getDatabasePath());
    
    // İlk kurulum verilerini yükle
    await setupDatabase();
    
  } catch (error) {
    console.error('❌ Veritabanı başlatma hatası:', error);
  }
  
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    // Veritabanı bağlantısını kapat
    closeDatabase();
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// Yazıcı Servisi
interface ReceiptData {
  items: Array<{
    name: string;
    quantity: number;
    price: number;
    total: number;
  }>;
  totalAmount: number;
  paymentMethod: string;
  timestamp: Date;
}

class PrinterService {
  async printReceipt(data: ReceiptData): Promise<boolean> {
    try {
      // Windows'ta yeni bir pencere oluştur ve yazdır
      const printWindow = new BrowserWindow({
        width: 300,
        height: 600,
        show: false,
        webPreferences: {
          nodeIntegration: true,
          contextIsolation: false
        }
      });

      // Fiş HTML içeriğini oluştur
      const receiptHTML = this.generateReceiptHTML(data);
      
      // HTML içeriğini yükle
      await printWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(receiptHTML)}`);
      
      // Yazdır
      await printWindow.webContents.print({
        silent: true, // Yazdırma dialogu gösterme
        printBackground: false,
        margins: {
          marginType: 'custom',
          top: 0,
          bottom: 0,
          left: 0,
          right: 0
        },
        pageSize: {
          width: 80000, // 80mm (termal yazıcı genişliği)
          height: 200000 // Uzun fiş
        }
      });

      // Pencereyi kapat
      printWindow.close();
      
      return true;
    } catch (error) {
      console.error('Yazıcı hatası:', error);
      return false;
    }
  }

  private generateReceiptHTML(data: ReceiptData): string {
    const now = new Date();
    const dateStr = now.toLocaleDateString('tr-TR');
    const timeStr = now.toLocaleTimeString('tr-TR');

    return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
          font-family: 'Courier New', monospace;
          font-size: 12px;
          line-height: 1.4;
          width: 80mm;
          margin: 0;
          padding: 10px;
          background: white;
        }
        .center { text-align: center; }
        .bold { font-weight: bold; }
        .line { border-top: 1px dashed #000; margin: 5px 0; }
        .header { margin-bottom: 10px; }
        .item { margin: 2px 0; display: flex; justify-content: space-between; }
        .total { margin-top: 10px; font-size: 14px; }
        .footer { margin-top: 15px; }
      </style>
    </head>
    <body>
      <div class="header center">
        <div class="bold" style="font-size: 16px;">TACKA KAFE</div>
        <div>Adres: Cafe Adresi</div>
        <div>Tel: 0XXX XXX XX XX</div>
        <div class="line"></div>
        <div><strong>FİŞ NO:</strong> ${Math.floor(Math.random() * 10000)}</div>
        <div><strong>TARİH:</strong> ${dateStr}</div>
        <div><strong>SAAT:</strong> ${timeStr}</div>
      </div>
      
      <div class="line"></div>
      
      <div class="items">
        ${data.items.map(item => `
          <div class="item">
            <span>${item.name}</span>
          </div>
          <div class="item">
            <span>${item.quantity} x ${item.price.toFixed(2)} TL</span>
            <span>${item.total.toFixed(2)} TL</span>
          </div>
        `).join('')}
      </div>
      
      <div class="line"></div>
      
      <div class="total center bold">
        <div style="font-size: 16px;">TOPLAM: ${data.totalAmount.toFixed(2)} TL</div>
        <div style="margin-top: 5px;">ÖDEME: ${data.paymentMethod}</div>
      </div>
      
      <div class="footer center">
        <div class="line"></div>
        <div>Bizi tercih ettiğiniz için</div>
        <div class="bold">TEŞEKKÜRLER!</div>
        <div style="margin-top: 10px; font-size: 10px;">
          Cafe POS Sistemi v1.0
        </div>
      </div>
    </body>
    </html>`;
  }
}

const printerService = new PrinterService();

// IPC Handlers
ipcMain.handle('print-receipt', async (event, receiptData: ReceiptData) => {
  return await printerService.printReceipt(receiptData);
});

// Pencere kontrol handlers
ipcMain.handle('toggle-fullscreen', async () => {
  if (mainWindow) {
    mainWindow.setFullScreen(!mainWindow.isFullScreen());
  }
});

ipcMain.handle('is-fullscreen', async () => {
  return mainWindow ? mainWindow.isFullScreen() : false;
});

// Database IPC Handlers
ipcMain.handle('db-get-categories', async () => {
  try {
    const db = getDatabase();
    return db.getCategories();
  } catch (error) {
    console.error('Database get categories error:', error);
    return [];
  }
});

ipcMain.handle('db-add-category', async (event, category) => {
  try {
    const db = getDatabase();
    return db.addCategory(category);
  } catch (error) {
    console.error('Database add category error:', error);
    return false;
  }
});

ipcMain.handle('db-update-category', async (event, id, updates) => {
  try {
    const db = getDatabase();
    return db.updateCategory(id, updates);
  } catch (error) {
    console.error('Database update category error:', error);
    return false;
  }
});

ipcMain.handle('db-delete-category', async (event, id) => {
  try {
    const db = getDatabase();
    return db.deleteCategory(id);
  } catch (error) {
    console.error('Database delete category error:', error);
    return false;
  }
});

ipcMain.handle('db-get-products', async () => {
  try {
    const db = getDatabase();
    return db.getProducts();
  } catch (error) {
    console.error('Database get products error:', error);
    return [];
  }
});

ipcMain.handle('db-get-products-by-category', async (event, categoryId) => {
  try {
    const db = getDatabase();
    return db.getProductsByCategory(categoryId);
  } catch (error) {
    console.error('Database get products by category error:', error);
    return [];
  }
});

ipcMain.handle('db-get-product-by-id', async (event, id) => {
  try {
    const db = getDatabase();
    return db.getProductById(id);
  } catch (error) {
    console.error('Database get product by id error:', error);
    return null;
  }
});

ipcMain.handle('db-add-product', async (event, product) => {
  try {
    const db = getDatabase();
    return db.addProduct(product);
  } catch (error) {
    console.error('Database add product error:', error);
    return false;
  }
});

ipcMain.handle('db-update-product', async (event, id, updates) => {
  try {
    const db = getDatabase();
    return db.updateProduct(id, updates);
  } catch (error) {
    console.error('Database update product error:', error);
    return false;
  }
});

ipcMain.handle('db-delete-product', async (event, id) => {
  try {
    const db = getDatabase();
    return db.deleteProduct(id);
  } catch (error) {
    console.error('Database delete product error:', error);
    return false;
  }
});

ipcMain.handle('db-get-setting', async (event, key) => {
  try {
    const db = getDatabase();
    return db.getSetting(key);
  } catch (error) {
    console.error('Database get setting error:', error);
    return null;
  }
});

ipcMain.handle('db-set-setting', async (event, key, value) => {
  try {
    const db = getDatabase();
    return db.setSetting(key, value);
  } catch (error) {
    console.error('Database set setting error:', error);
    return false;
  }
});

ipcMain.handle('db-save-password', async (event, password) => {
  try {
    const db = getDatabase();
    return db.savePassword(password);
  } catch (error) {
    console.error('Database save password error:', error);
    return false;
  }
});

ipcMain.handle('db-load-password', async () => {
  try {
    const db = getDatabase();
    return db.loadPassword();
  } catch (error) {
    console.error('Database load password error:', error);
    return null;
  }
});

ipcMain.handle('db-save-categories', async (event, categories) => {
  try {
    const db = getDatabase();
    return db.saveCategories(categories);
  } catch (error) {
    console.error('Database save categories error:', error);
    return false;
  }
});

ipcMain.handle('db-save-products', async (event, products) => {
  try {
    const db = getDatabase();
    return db.saveProducts(products);
  } catch (error) {
    console.error('Database save products error:', error);
    return false;
  }
});

ipcMain.handle('db-clear-all-data', async () => {
  try {
    const db = getDatabase();
    return db.clearAllData();
  } catch (error) {
    console.error('Database clear all data error:', error);
    return false;
  }
});

ipcMain.handle('db-get-database-path', async () => {
  try {
    const db = getDatabase();
    return db.getDatabasePath();
  } catch (error) {
    console.error('Database get path error:', error);
    return '';
  }
});

ipcMain.handle('db-save-sale', async (event, sale) => {
  try {
    const db = getDatabase();
    return db.saveSale(sale);
  } catch (error) {
    console.error('Database save sale error:', error);
    return false;
  }
});

ipcMain.handle('db-get-all-sales', async () => {
  try {
    const db = getDatabase();
    return db.getAllSales();
  } catch (error) {
    console.error('Database get all sales error:', error);
    return [];
  }
});

ipcMain.handle('db-get-dashboard-stats', async () => {
  try {
    const db = getDatabase();
    return db.getDashboardStats();
  } catch (error) {
    console.error('Database get dashboard stats error:', error);
    return null;
  }
});

// Uygulama kapatılırken veritabanını temiz şekilde kapat
app.on('before-quit', () => {
  closeDatabase();
});

ipcMain.handle('get-printers', async () => {
  // Windows'ta bulunan yazıcıları listele
  return [];
});

// Masa siparişleri IPC handlers
ipcMain.handle('db-get-active-table-orders', async () => {
  console.log('🔄 IPC Handler çağrıldı: db-get-active-table-orders');
  try {
    const db = getDatabase();
    console.log('📊 Database instance alındı');
    const result = db.getActiveTableOrders();
    console.log('✅ Aktif masa siparişleri alındı:', Object.keys(result).length, 'masa');
    return result;
  } catch (error) {
    console.error('❌ Database get active table orders error:', error);
    return {};
  }
});

ipcMain.handle('db-save-table-order', async (event, tableNumber, items, total) => {
  console.log('🔄 IPC Handler çağrıldı: db-save-table-order', { tableNumber, itemsCount: items?.length || 0, total });
  try {
    // Veri doğrulama
    if (!tableNumber || tableNumber <= 0) {
      console.error('❌ Geçersiz masa numarası:', tableNumber);
      return false;
    }

    if (!items || items.length === 0) {
      console.error('❌ Sipariş öğeleri boş');
      return false;
    }

    if (!total || total <= 0) {
      console.error('❌ Geçersiz toplam tutar:', total);
      return false;
    }

    const db = getDatabase();
    const result = db.saveTableOrder(tableNumber, items, total);
    console.log('✅ Masa siparişi kaydedildi:', result);
    return result;
  } catch (error) {
    console.error('❌ Database save table order error:', error);
    return false;
  }
});

ipcMain.handle('db-add-to-table-order', async (event, tableNumber, items, total) => {
  console.log('🔄 IPC Handler çağrıldı: db-add-to-table-order', { tableNumber, itemsCount: items?.length || 0, total });
  try {
    // Veri doğrulama
    if (!tableNumber || tableNumber <= 0) {
      console.error('❌ Geçersiz masa numarası:', tableNumber);
      return false;
    }

    if (!items || items.length === 0) {
      console.error('❌ Sipariş öğeleri boş');
      return false;
    }

    if (!total || total <= 0) {
      console.error('❌ Geçersiz toplam tutar:', total);
      return false;
    }

    const db = getDatabase();
    const result = db.addToTableOrder(tableNumber, items, total);
    console.log('✅ Masaya sipariş eklendi:', result);
    return result;
  } catch (error) {
    console.error('❌ Database add to table order error:', error);
    return false;
  }
});

ipcMain.handle('db-close-table-order', async (event, tableNumber) => {
  console.log('🔄 IPC Handler çağrıldı: db-close-table-order', { tableNumber });
  try {
    // Veri doğrulama
    if (!tableNumber || tableNumber <= 0) {
      console.error('❌ Geçersiz masa numarası:', tableNumber);
      return false;
    }

    const db = getDatabase();
    const result = db.closeTableOrder(tableNumber);
    console.log('✅ Masa siparişi kapatıldı:', result);
    return result;
  } catch (error) {
    console.error('❌ Database close table order error:', error);
    return false;
  }
});

// Müşteri işlemleri IPC handlers
ipcMain.handle('db-get-customers', async () => {
  console.log('🔄 IPC Handler çağrıldı: db-get-customers');
  try {
    const db = getDatabase();
    console.log('📡 Database instance alındı, getCustomers çağrılıyor...');
    const list = db.getCustomers();
    console.log('📋 getCustomers sonucu:', list);
    console.log('👥 Müşteri sayısı:', list?.length || 0);
    return list;
  } catch (error) {
    console.error('❌ Database get customers error:', error);
    return [];
  }
});
console.log('🔧 db-get-customers handler kaydedildi');

ipcMain.handle('db-add-customer', async (event, name: string, phone?: string) => {
  console.log('🔄 IPC Handler çağrıldı: db-add-customer', { name, phone });
  try {
    if (!name || !name.trim()) {
      console.error('❌ Geçersiz müşteri adı:', name);
      return null;
    }
    console.log('📡 Database instance alındı, addCustomer çağrılıyor...');
    const db = getDatabase();
    const row = db.addCustomer(name.trim(), phone?.trim() || null);
    const ok = !!row && !!row.id;
    console.log('✅ db-add-customer sonucu:', ok, row);
    return row ?? null;
  } catch (error) {
    console.error('❌ Database add customer error:', error);
    return null;
  }
});
console.log('🔧 db-add-customer handler kaydedildi');

ipcMain.handle('db-delete-all-customers', async () => {
  console.log('🔄 IPC Handler çağrıldı: db-delete-all-customers');
  try {
    const db = getDatabase();
    const result = db.deleteAllCustomers();
    console.log('✅ db-delete-all-customers sonucu:', result);
    return result;
  } catch (error) {
    console.error('❌ Database delete all customers error:', error);
    return false;
  }
});
console.log('🔧 db-delete-all-customers handler kaydedildi');

ipcMain.handle('db-add-customer-order', async (event, customerId: number, items: any[], totalAmount: number, paymentMethod?: string) => {
  console.log('🔄 IPC Handler çağrıldı: db-add-customer-order', { customerId, totalAmount, paymentMethod });
  try {
    const db = getDatabase();
    const result = db.addCustomerOrder(customerId, items, totalAmount, paymentMethod);
    console.log('✅ db-add-customer-order sonucu:', result);
    return result;
  } catch (error) {
    console.error('❌ Database add customer order error:', error);
    return false;
  }
});
console.log('🔧 db-add-customer-order handler kaydedildi');

ipcMain.handle('db-get-customer-orders', async (event, customerId: number) => {
  console.log('🔄 IPC Handler çağrıldı: db-get-customer-orders', { customerId });
  try {
    const db = getDatabase();
    const result = db.getCustomerOrders(customerId);
    console.log('✅ db-get-customer-orders sonucu:', result);
    return result;
  } catch (error) {
    console.error('❌ Database get customer orders error:', error);
    return [];
  }
});
console.log('🔧 db-get-customer-orders handler kaydedildi');

ipcMain.handle('db-get-customer-total-debt', async (event, customerId: number) => {
  console.log('🔄 IPC Handler çağrıldı: db-get-customer-total-debt', { customerId });
  try {
    const db = getDatabase();
    const result = db.getCustomerTotalDebt(customerId);
    console.log('✅ db-get-customer-total-debt sonucu:', result);
    return result;
  } catch (error) {
    console.error('❌ Database get customer total debt error:', error);
    return 0;
  }
});
console.log('🔧 db-get-customer-total-debt handler kaydedildi');

ipcMain.handle('db-transfer-table-order', async (event, sourceTable: number, targetTable: number) => {
  console.log('🔄 IPC Handler çağrıldı: db-transfer-table-order', { sourceTable, targetTable });
  try {
    const db = getDatabase();
    const result = db.transferTableOrder(sourceTable, targetTable);
    console.log('✅ db-transfer-table-order sonucu:', result);
    return result;
  } catch (error) {
    console.error('❌ Database transfer table order error:', error);
    return false;
  }
});
console.log('🔧 db-transfer-table-order handler kaydedildi');

console.log('🔧 IPC Handlers kaydediliyor...');
console.log('🔧 db-get-active-table-orders handler kaydedildi');
console.log('🔧 db-save-table-order handler kaydedildi');
console.log('🔧 db-add-to-table-order handler kaydedildi');
console.log('🔧 db-close-table-order handler kaydedildi');
console.log('🔧 db-get-customers handler kaydedildi');
console.log('🔧 db-add-customer handler kaydedildi');
console.log('🔧 db-transfer-table-order handler kaydedildi');
